# Configuration for local development profile
# Activated when SPRING_PROFILES_ACTIVE=local (default if not specified)

server:
  port: 8080
  servlet:
    context-path: /

app:
  base-url: http://localhost:8080

# OpenAPI/Swagger Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

# GraphQL Configuration always enabled for local
spring.graphql.graphiql.enabled: true

# Logging Configuration for local development
logging:
  level:
    com.dm.ecommerce: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG 