spring:
  profiles: local

server:
  port: 8080
  servlet:
    context-path: /

app:
  base-url: http://localhost:8080

# OpenAPI/Swagger Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# Logging Configuration for local development
logging:
  level:
    com.dm.ecommerce: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG 